/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorial',
    },
  ],
  swiftuiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'swiftui',
    },
  ],
  swiftVaporSidebar: [
    {
      type: 'autogenerated',
      dirName: 'swift-vapor',
    },
  ],
  reactnativeSidebar: [
    {
      type: 'autogenerated',
      dirName: 'reactnative',
    },
  ],
  reactNextSidebar: [
    {
      type: 'autogenerated',
      dirName: 'react-next',
    },
  ],
  jsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'js',
    },
  ],
  htmlSidebar: [
    {
      type: 'autogenerated',
      dirName: 'html',
    },
  ],
  cssSidebar: [
    {
      type: 'autogenerated',
      dirName: 'css',
    },
  ],
  ant_designSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ant_design',
    },
  ],
  ts_designSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ts',
    },
  ],
  react_designSidebar: [
    {
      type: 'autogenerated',
      dirName: 'react',
    },
  ],
  java_designSidebar: [
    {
      type: 'autogenerated',
      dirName: 'java',
    },
  ],
  pm_coding_designSidebar: [
    {
      type: 'autogenerated',
      dirName: 'pm_coding',
    },
  ],
  db_designSidebar: [
    {
      type: 'autogenerated',
      dirName: 'db',
    },
  ],
  nodeSidebar: [
    {
      type: 'autogenerated',
      dirName: 'node',
    },
  ],
  linux_designSidebar: [
    {
      type: 'autogenerated',
      dirName: 'linux',
    },
  ],
  npm_designSidebar: [
    {
      type: 'autogenerated',
      dirName: 'npm',
    },
  ],
  flutter_designSidebar: [
    {
      type: 'autogenerated',
      dirName: 'flutter',
    },
  ],
};

export default sidebars;
